// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqirkfruupjpvoahyavr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxaXJrZnJ1dXBqcHZvYWh5YXZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNjAxNjEsImV4cCI6MjA1NDYzNjE2MX0.TTTJ3GChQ4oYs5tppYdILZgxnpE590E-Ex4_ba4D6Ug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);